name: Run test suite for MyHtop

on: push

jobs:
   run:
       name: "Run tests"
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v5

       - name: Install uv
         uses: astral-sh/setup-uv@v6
         with:
           enable-cache: true
           cache-dependency-glob: uv.lock

       - name: Set up Python
         run: uv python install 3.13
        
       # - name: "Run pytest on prac 2.1"
       #   run: uv run pytest test/prac_2_1/
       #
       # - name: "Run pytest on prac 2.2"
       #   run: uv run pytest test/prac_2_2/
       #
       # - name: "Run pytest on prac 2.3"
       #   run: uv run pytest test/prac_2_3/
       #
       # - name: "Run pytest on all the project"
       #   run: uv run coverage run -m pytest  -v -s
       #
       # - name: "Generate code coverage report"
       #   run: uv run coverage report -m
